In [1]:
import pandas as pd
path = "data/data_set_final.csv"
df = pd.read_csv(path)
df.head()

,type_de_carte,numero_de_carte,iban,prenom,nom,tel,email,date,adresse
0,Visa,4998333238637277,DS37936440816724157701,Ivan,Mohamed,33680486413,tUu5fP+nv15mmGo@gmail.com,2020-02-28 16:28:33,Route de Trevoux
1,Visa,4532989368815505,FO78770806307492557678,Ali,Hernandez,33329296055,1YuPVVB-Gvi+x5.CIkg@outlook.fr,2020-10-26 05:43:01,Rue Sainte Marie
2,Visa,4916767269587027,DQ9238775804852330416,Jack,Gashi,33696895947,ieC_jKCrZ0QC@yahoo.com,2020-01-12 02:15:45,1711 Route d’Hauteville
3,Visa,4485065267473279,FK06039258104715174116,Eric,Tamm,33529876356,wHUsh.q54tw@hotmail.com,2018-07-19 07:49:07,Route du Morbier
4,Visa,4929375970407322,BD861759585735010721,Mohammed,Kumar,33453210957,NTb_kGY-8@me.io,2020-05-18 09:56:24,Rue des Bleuets

In [2]:
df_test = df.iloc[:20]
list_device = ["Iphone", "Iphone de Julien", "Iphone X", "Iphone De Nicolas", "Iphone's Antoine", \
                    "Apple Watch De Pierre", "Iphone de Romain", "Apple Watch de Pierre", "Iphone De Damien", "Iphone", \
                    "Doom 8", "Iphone Luc", "Iphone old", "Macbook Pro de Alex", "Apple Watch's Simon", \
                    "Macbook Pro d'Alex", "Iphone De Clément", "Iphone De Gru", "Machin", "Iphone 6 Fafa"]
df_test["device"] = list_device
df_test = df_test.drop(["type_de_carte", "nom", "email", "numero_de_carte"], axis = 1)
df_test

<ipython-input-2-23523993edf9>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test["device"] = list_device

,iban,prenom,tel,date,adresse,device
0,DS37936440816724157701,Ivan,33680486413,2020-02-28 16:28:33,Route de Trevoux,Iphone
1,FO78770806307492557678,Ali,33329296055,2020-10-26 05:43:01,Rue Sainte Marie,Iphone de Julien
2,DQ9238775804852330416,Jack,33696895947,2020-01-12 02:15:45,1711 Route d’Hauteville,Iphone X
3,FK06039258104715174116,Eric,33529876356,2018-07-19 07:49:07,Route du Morbier,Iphone De Nicolas
4,BD861759585735010721,Mohammed,33453210957,2020-05-18 09:56:24,Rue des Bleuets,Iphone's Antoine
5,HH599125807329265829,Anthony,891788852,2019-12-30 18:17:27,7 Rue Jean Monnet,Apple Watch De Pierre
6,BE8889711730748898116,Ahmad,33764281361,2019-07-07 01:01:30,193 Chemin de Chavagneux,Iphone de Romain
7,ZD55031363568301494883,Jose,299296783,2018-06-14 19:35:14,55 Rue du Coteau,Apple Watch de Pierre
8,SF89684024927071652922,Chan,869199084,2018-02-16 12:00:16,Rue de l’Eglise,Iphone De Damien
9,YJ07585923250813271912,Mehmet,213744666,2019-12-01 20:28:38,89 Impasse des Chênes,Iphone
10,XK156172020072837459,Nikola,33549241234,2020-03-07 22:53:31,Rue du Journans,Doom 8
11,AA8036533918308092930,László,222663388,2019-11-09 22:23:30,Rue de la Rogeraie,Iphone Luc
12,KT2407301263449503188,Thato,210259530,2020-04-15 09:22:15,3 Au Bourg,Iphone old
13,QQ2846142388397585634,Anna,33735553929,2020-07-06 11:40:50,12 Rue Jean Emery,Macbook Pro de Alex
14,VE6127835849976181696,Maria,33652197808,2018-02-11 11:28:11,Rue du Dauphiné,Apple Watch's Simon
15,CK38957132493651668755,Marko,533964737,2020-12-18 13:55:38,162 Route de Bottenay,Macbook Pro d'Alex
16,WU88974639302605843025,Mark,33954974238,2020-04-23 13:40:48,Rue de la Doy,Iphone De Clément
17,IJ601751686757542961,Jan,845240639,2018-01-31 16:00:30,Rue des Colonnes,Iphone De Gru
18,NQ65853779547749767376,Marie,33874156254,2019-01-04 20:24:02,541 Route du Boissonnet,Machin
19,ST2084230660230930181,David,264908293,2019-06-28 00:19:30,Route de Bourg,Iphone 6 Fafa

In [3]:
import pyspark.sql.functions as F
from pyspark.sql.window import Window
from sparknlp.annotator import *
from sparknlp.base import *
import sparknlp
from sparknlp.pretrained import PretrainedPipeline

spark = sparknlp.start()

In [4]:
print("Spark NLP version: {}".format(sparknlp.version()))
print("Apache Spark version: {}".format(spark.version))

Spark NLP version: 3.3.2
Apache Spark version: 3.1.2

In [5]:
pipeline = PretrainedPipeline.from_disk('entity_recognizer_lg_fr')

In [6]:
df_spark = spark.createDataFrame(df_test)
df_spark.show(truncate = False)

+----------------------+--------+-----------+-------------------+------------------------+---------------------+
|iban                  |prenom  |tel        |date               |adresse                 |device               |
+----------------------+--------+-----------+-------------------+------------------------+---------------------+
|DS37936440816724157701|Ivan    |33680486413|2020-02-28 16:28:33|Route de Trevoux        |Iphone               |
|FO78770806307492557678|Ali     |33329296055|2020-10-26 05:43:01|Rue Sainte Marie        |Iphone de Julien     |
|DQ9238775804852330416 |Jack    |33696895947|2020-01-12 02:15:45|1711 Route d’Hauteville |Iphone X             |
|FK06039258104715174116|Eric    |33529876356|2018-07-19 07:49:07|Route du Morbier        |Iphone De Nicolas    |
|BD861759585735010721  |Mohammed|33453210957|2020-05-18 09:56:24|Rue des Bleuets         |Iphone's Antoine     |
|HH599125807329265829  |Anthony |891788852  |2019-12-30 18:17:27|7 Rue Jean Monnet       |Apple Watch De Pierre|
|BE8889711730748898116 |Ahmad   |33764281361|2019-07-07 01:01:30|193 Chemin de Chavagneux|Iphone de Romain     |
|ZD55031363568301494883|Jose    |299296783  |2018-06-14 19:35:14|55 Rue du Coteau        |Apple Watch de Pierre|
|SF89684024927071652922|Chan    |869199084  |2018-02-16 12:00:16|Rue de l’Eglise         |Iphone De Damien     |
|YJ07585923250813271912|Mehmet  |213744666  |2019-12-01 20:28:38|89 Impasse des Chênes   |Iphone               |
|XK156172020072837459  |Nikola  |33549241234|2020-03-07 22:53:31|Rue du Journans         |Doom 8               |
|AA8036533918308092930 |László  |222663388  |2019-11-09 22:23:30|Rue de la Rogeraie      |Iphone Luc           |
|KT2407301263449503188 |Thato   |210259530  |2020-04-15 09:22:15|3 Au Bourg              |Iphone old           |
|QQ2846142388397585634 |Anna    |33735553929|2020-07-06 11:40:50|12 Rue Jean Emery       |Macbook Pro de Alex  |
|VE6127835849976181696 |Maria   |33652197808|2018-02-11 11:28:11|Rue du Dauphiné         |Apple Watch's Simon  |
|CK38957132493651668755|Marko   |533964737  |2020-12-18 13:55:38|162 Route de Bottenay   |Macbook Pro d'Alex   |
|WU88974639302605843025|Mark    |33954974238|2020-04-23 13:40:48|Rue de la Doy           |Iphone De Clément    |
|IJ601751686757542961  |Jan     |845240639  |2018-01-31 16:00:30|Rue des Colonnes        |Iphone De Gru        |
|NQ65853779547749767376|Marie   |33874156254|2019-01-04 20:24:02|541 Route du Boissonnet |Machin               |
|ST2084230660230930181 |David   |264908293  |2019-06-28 00:19:30|Route de Bourg          |Iphone 6 Fafa        |
+----------------------+--------+-----------+-------------------+------------------------+---------------------+

In [8]:
def get_entity(column):
        data = df_spark.select(column).toDF("text")
        annotations = pipeline.transform(data)
        
        result = annotations.withColumn("id", F.monotonically_increasing_id()).select("id", "text", "entities")
        result = result.select(F.col("id"), F.col("text"), F.col("entities.result").alias("result"), F.explode("entities.metadata"))
        result = result.select("id", "text", "result", F.col("col.entity").alias("predict"))
        result = result.groupby("id", "predict").agg(F.count("predict").alias("count"))

        w = Window.partitionBy("id").orderBy(F.col("count").desc())

        result = result.withColumn("row", F.row_number().over(w)) \
                        .filter(F.col("row") == 1) \
                        .drop("row", "count") \
                        .groupby("predict").count()
        
        result = result.toPandas()
        
        other_row = {'predict': 'OTHER', 'count': annotations.count() - sum(result.loc[result.predict != 'MISC']['count'])}
        result = result.append(other_row, ignore_index = True)
        result.drop(result[result.predict == 'MISC'].index, inplace = True)
        result.sort_values(by = ['count'], ascending = False, inplace = True)
        
        return result

In [9]:
'''
for c in df_spark.columns:
    result = get_entity(c)
    predict = result.iloc[0]['predict']
    if predict != "OTHER":
        print("Donnée structurée - 1")
        print(c, ":", predict)
        #print(result)
    else:
        letter_avg = df_spark.agg(F.mean(F.length(F.regexp_replace(F.col(c), '[^a-zA-Z]', "")))).collect()[0][0]
        word_avg = df_spark.agg(F.mean(F.size(F.split(F.col(c), " ")))).collect()[0][0]
        if letter_avg > 1.0 and word_avg > 1.0:
            print("Donnée non structurée")
            print(c)
        else:
            print("Donnée structurée - 2")
            print(c, ":", predict)
'''

'\nfor c in df_spark.columns:\n    result = get_entity(c)\n    predict = result.iloc[0][\'predict\']\n    if predict != "OTHER":\n        print("Donnée structurée - 1")\n        print(c, ":", predict)\n        #print(result)\n    else:\n        letter_avg = df_spark.agg(F.mean(F.length(F.regexp_replace(F.col(c), \'[^a-zA-Z]\', "")))).collect()[0][0]\n        word_avg = df_spark.agg(F.mean(F.size(F.split(F.col(c), " ")))).collect()[0][0]\n        if letter_avg >= 1.0 and word_avg >= 1.0:\n            print("Donnée non structurée")\n            print(c)\n        else:\n            print("Donnée structurée - 2")\n            print(c, ":", predict)\n'

In [10]:
data = df_spark.select("device").toDF("text")
annotations = pipeline.transform(data)
result = annotations.select(F.col("text"), F.col("ner.result").alias("ner"), F.col("entities.result").alias("text ner_chunk"), F.col("entities.metadata").alias("ner_chunk"))
result.show(truncate = False)

+---------------------+----------------------------+-----------------------+-----------------------------------------------------------------------------------------+
|text                 |ner                         |text ner_chunk         |ner_chunk                                                                                |
+---------------------+----------------------------+-----------------------+-----------------------------------------------------------------------------------------+
|Iphone               |[I-MISC]                    |[Iphone]               |[{entity -> MISC, sentence -> 0, chunk -> 0}]                                            |
|Iphone de Julien     |[I-MISC, O, I-PER]          |[Iphone, Julien]       |[{entity -> MISC, sentence -> 0, chunk -> 0}, {entity -> PER, sentence -> 0, chunk -> 1}]|
|Iphone X             |[I-MISC, I-MISC]            |[Iphone X]             |[{entity -> MISC, sentence -> 0, chunk -> 0}]                                            |
|Iphone De Nicolas    |[I-MISC, I-MISC, I-MISC]    |[Iphone De Nicolas]    |[{entity -> MISC, sentence -> 0, chunk -> 0}]                                            |
|Iphone's Antoine     |[I-LOC, I-PER]              |[Iphone's Antoine]     |[{entity -> LOC, sentence -> 0, chunk -> 0}]                                             |
|Apple Watch De Pierre|[I-ORG, I-ORG, I-ORG, I-ORG]|[Apple Watch De Pierre]|[{entity -> ORG, sentence -> 0, chunk -> 0}]                                             |
|Iphone de Romain     |[O, O, I-PER]               |[Romain]               |[{entity -> PER, sentence -> 0, chunk -> 0}]                                             |
|Apple Watch de Pierre|[I-ORG, I-ORG, O, I-PER]    |[Apple Watch, Pierre]  |[{entity -> ORG, sentence -> 0, chunk -> 0}, {entity -> PER, sentence -> 0, chunk -> 1}] |
|Iphone De Damien     |[I-MISC, I-MISC, I-MISC]    |[Iphone De Damien]     |[{entity -> MISC, sentence -> 0, chunk -> 0}]                                            |
|Iphone               |[I-MISC]                    |[Iphone]               |[{entity -> MISC, sentence -> 0, chunk -> 0}]                                            |
|Doom 8               |[I-MISC, I-MISC]            |[Doom 8]               |[{entity -> MISC, sentence -> 0, chunk -> 0}]                                            |
|Iphone Luc           |[I-MISC, I-MISC]            |[Iphone Luc]           |[{entity -> MISC, sentence -> 0, chunk -> 0}]                                            |
|Iphone old           |[I-MISC, I-MISC]            |[Iphone old]           |[{entity -> MISC, sentence -> 0, chunk -> 0}]                                            |
|Macbook Pro de Alex  |[I-MISC, I-MISC, O, I-PER]  |[Macbook Pro, Alex]    |[{entity -> MISC, sentence -> 0, chunk -> 0}, {entity -> PER, sentence -> 0, chunk -> 1}]|
|Apple Watch's Simon  |[I-ORG, I-ORG, I-ORG]       |[Apple Watch's Simon]  |[{entity -> ORG, sentence -> 0, chunk -> 0}]                                             |
|Macbook Pro d'Alex   |[I-MISC, I-MISC, I-MISC]    |[Macbook Pro d'Alex]   |[{entity -> MISC, sentence -> 0, chunk -> 0}]                                            |
|Iphone De Clément    |[I-MISC, I-MISC, I-MISC]    |[Iphone De Clément]    |[{entity -> MISC, sentence -> 0, chunk -> 0}]                                            |
|Iphone De Gru        |[I-MISC, I-MISC, I-MISC]    |[Iphone De Gru]        |[{entity -> MISC, sentence -> 0, chunk -> 0}]                                            |
|Machin               |[I-PER]                     |[Machin]               |[{entity -> PER, sentence -> 0, chunk -> 0}]                                             |
|Iphone 6 Fafa        |[I-MISC, I-MISC, I-MISC]    |[Iphone 6 Fafa]        |[{entity -> MISC, sentence -> 0, chunk -> 0}]                                            |
+---------------------+----------------------------+-----------------------+-----------------------------------------------------------------------------------------+